/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    characters: Character;
    'dialogue-lines': DialogueLine;
    weapons: Weapon;
    items: Item;
    'audio-assets': AudioAsset;
    'image-assets': ImageAsset;
    'content-projects': ContentProject;
    'content-schema-imports': ContentSchemaImport;
    'content-pack-documents': ContentPackDocument;
    'content-custom-schemas': ContentCustomSchema;
    'content-platform-data': ContentPlatformDatum;
    'content-draft-revisions': ContentDraftRevision;
    'content-publish-jobs': ContentPublishJob;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'dialogue-lines': DialogueLinesSelect<false> | DialogueLinesSelect<true>;
    weapons: WeaponsSelect<false> | WeaponsSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    'audio-assets': AudioAssetsSelect<false> | AudioAssetsSelect<true>;
    'image-assets': ImageAssetsSelect<false> | ImageAssetsSelect<true>;
    'content-projects': ContentProjectsSelect<false> | ContentProjectsSelect<true>;
    'content-schema-imports': ContentSchemaImportsSelect<false> | ContentSchemaImportsSelect<true>;
    'content-pack-documents': ContentPackDocumentsSelect<false> | ContentPackDocumentsSelect<true>;
    'content-custom-schemas': ContentCustomSchemasSelect<false> | ContentCustomSchemasSelect<true>;
    'content-platform-data': ContentPlatformDataSelect<false> | ContentPlatformDataSelect<true>;
    'content-draft-revisions': ContentDraftRevisionsSelect<false> | ContentDraftRevisionsSelect<true>;
    'content-publish-jobs': ContentPublishJobsSelect<false> | ContentPublishJobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'generate-dialogue-audio': TaskGenerateDialogueAudio;
      'generate-weapon-sfx': TaskGenerateWeaponSfx;
      'generate-item-sfx': TaskGenerateItemSfx;
      'generate-character-image': TaskGenerateCharacterImage;
      'generate-weapon-image': TaskGenerateWeaponImage;
      'generate-item-image': TaskGenerateItemImage;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Owner: Full system access. Admin: Can create users and content. User: Read-only access. Admins will automatically create users with 'user' role.
   */
  role?: ('owner' | 'admin' | 'user') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  name: string;
  slug: string;
  summary?: string | null;
  /**
   * Optional canonical entity type or authored content id from the current game contracts.
   */
  canonicalEntityId?: string | null;
  /**
   * Optional canonical trait ids carried alongside this character draft.
   */
  traitIds?: string[] | null;
  /**
   * Default ElevenLabs voice for this character.
   */
  voiceId?: string | null;
  voiceModelId?: string | null;
  /**
   * Prompt used when generating portrait concept art.
   */
  portraitPrompt?: string | null;
  latestPortrait?: (number | null) | ImageAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-assets".
 */
export interface ImageAsset {
  id: number;
  assetType: 'character_portrait' | 'weapon_art' | 'item_art';
  provider: 'openai';
  status: 'queued' | 'processing' | 'succeeded' | 'failed';
  prompt: string;
  model: string;
  size: '1024x1024' | '1024x1536' | '1536x1024';
  quality: 'auto' | 'low' | 'medium' | 'high';
  media?: (number | null) | Media;
  character?: (number | null) | Character;
  weapon?: (number | null) | Weapon;
  item?: (number | null) | Item;
  jobID?: string | null;
  providerRequestID?: string | null;
  idempotencyKey?: string | null;
  errorMessage?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons".
 */
export interface Weapon {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Prompt for ElevenLabs weapon SFX generation.
   */
  soundEffectPrompt: string;
  /**
   * Prompt for OpenAI weapon art generation.
   */
  imagePrompt?: string | null;
  audioModelId?: string | null;
  audioSeed?: number | null;
  latestAudioAsset?: (number | null) | AudioAsset;
  latestImageAsset?: (number | null) | ImageAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-assets".
 */
export interface AudioAsset {
  id: number;
  assetType: 'dialogue_voice' | 'weapon_sfx' | 'item_sfx';
  provider: 'elevenlabs';
  status: 'queued' | 'processing' | 'succeeded' | 'failed';
  sourceTextOrPrompt: string;
  voiceId: string;
  modelId: string;
  durationSeconds?: number | null;
  seed?: number | null;
  media?: (number | null) | Media;
  character?: (number | null) | Character;
  dialogueLine?: (number | null) | DialogueLine;
  weapon?: (number | null) | Weapon;
  item?: (number | null) | Item;
  jobID?: string | null;
  providerRequestID?: string | null;
  idempotencyKey?: string | null;
  errorMessage?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dialogue-lines".
 */
export interface DialogueLine {
  id: number;
  label: string;
  slug: string;
  character: number | Character;
  /**
   * Optional canonical dialogue id from the current game content packs.
   */
  canonicalDialogId?: string | null;
  scene?: string | null;
  lineText: string;
  /**
   * Optional override for ElevenLabs voice ID.
   */
  audioVoiceId?: string | null;
  /**
   * Optional override for ElevenLabs model.
   */
  audioModelId?: string | null;
  /**
   * Optional seed for deterministic generation.
   */
  audioSeed?: number | null;
  latestAudioAsset?: (number | null) | AudioAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Prompt for ElevenLabs item-use SFX generation.
   */
  soundEffectPrompt: string;
  /**
   * Prompt for OpenAI item art generation.
   */
  imagePrompt?: string | null;
  audioModelId?: string | null;
  audioSeed?: number | null;
  latestAudioAsset?: (number | null) | AudioAsset;
  latestImageAsset?: (number | null) | ImageAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-projects".
 */
export interface ContentProject {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  status: 'draft' | 'validated' | 'published';
  /**
   * Directory under docs-site where exported contract-shaped files are written.
   */
  exportRoot: string;
  sourceMode: 'payload';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-schema-imports".
 */
export interface ContentSchemaImport {
  id: number;
  key: string;
  project: number | ContentProject;
  packId: string;
  title: string;
  kind: string;
  exportName: string;
  sourceFile: string;
  bundleKey?: string | null;
  contentSourcePath?: string | null;
  schemaVersion?: string | null;
  schemaRef?: string | null;
  topLevelCounts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  canonicalDocument?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  importStatus: 'imported' | 'refreshed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-pack-documents".
 */
export interface ContentPackDocument {
  id: number;
  key: string;
  project: number | ContentProject;
  schemaImport?: (number | null) | ContentSchemaImport;
  packId: string;
  title: string;
  kind: string;
  exportName: string;
  sourceFile: string;
  bundleKey?: string | null;
  contentSourcePath?: string | null;
  schemaVersion?: string | null;
  document:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'imported' | 'edited' | 'exported';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-custom-schemas".
 */
export interface ContentCustomSchema {
  id: number;
  key: string;
  project: number | ContentProject;
  schemaId: string;
  name: string;
  /**
   * Optional pack or pack-family this schema extends.
   */
  targetPackId?: string | null;
  schemaType: 'json-schema' | 'object-schema' | 'canonical-asset';
  document:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'validated' | 'exported';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-platform-data".
 */
export interface ContentPlatformDatum {
  id: number;
  key: string;
  project: number | ContentProject;
  dataId: string;
  name: string;
  /**
   * Fixed project-data authoring surface for this collection. Runtime consumer decoration belongs in canonical content or a later delivery layer.
   */
  platformLayer: 'docs-site-payloadcms';
  namespace: 'admin-ui' | 'workflow' | 'publishing' | 'rendering' | 'integration' | 'generic-extension';
  /**
   * Optional canonical pack/schema/entity id this docs-site/Payload authoring record decorates.
   */
  targetId?: string | null;
  document:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'validated' | 'exported';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-draft-revisions".
 */
export interface ContentDraftRevision {
  id: number;
  key: string;
  project: number | ContentProject;
  targetType: 'pack-document' | 'custom-schema' | 'platform-data';
  targetKey: string;
  targetName: string;
  targetDocumentId: string;
  changeKind: 'import' | 'edit' | 'publish';
  notes?: string | null;
  document:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-publish-jobs".
 */
export interface ContentPublishJob {
  id: number;
  jobId: string;
  project: number | ContentProject;
  status: 'running' | 'succeeded' | 'failed';
  exportRoot?: string | null;
  commands?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  exportFiles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  engineFiles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  skippedPacks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorMessage?: string | null;
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'generate-dialogue-audio'
          | 'generate-weapon-sfx'
          | 'generate-item-sfx'
          | 'generate-character-image'
          | 'generate-weapon-image'
          | 'generate-item-image';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'generate-dialogue-audio'
        | 'generate-weapon-sfx'
        | 'generate-item-sfx'
        | 'generate-character-image'
        | 'generate-weapon-image'
        | 'generate-item-image'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'dialogue-lines';
        value: number | DialogueLine;
      } | null)
    | ({
        relationTo: 'weapons';
        value: number | Weapon;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'audio-assets';
        value: number | AudioAsset;
      } | null)
    | ({
        relationTo: 'image-assets';
        value: number | ImageAsset;
      } | null)
    | ({
        relationTo: 'content-projects';
        value: number | ContentProject;
      } | null)
    | ({
        relationTo: 'content-schema-imports';
        value: number | ContentSchemaImport;
      } | null)
    | ({
        relationTo: 'content-pack-documents';
        value: number | ContentPackDocument;
      } | null)
    | ({
        relationTo: 'content-custom-schemas';
        value: number | ContentCustomSchema;
      } | null)
    | ({
        relationTo: 'content-platform-data';
        value: number | ContentPlatformDatum;
      } | null)
    | ({
        relationTo: 'content-draft-revisions';
        value: number | ContentDraftRevision;
      } | null)
    | ({
        relationTo: 'content-publish-jobs';
        value: number | ContentPublishJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  canonicalEntityId?: T;
  traitIds?: T;
  voiceId?: T;
  voiceModelId?: T;
  portraitPrompt?: T;
  latestPortrait?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dialogue-lines_select".
 */
export interface DialogueLinesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  character?: T;
  canonicalDialogId?: T;
  scene?: T;
  lineText?: T;
  audioVoiceId?: T;
  audioModelId?: T;
  audioSeed?: T;
  latestAudioAsset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons_select".
 */
export interface WeaponsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  soundEffectPrompt?: T;
  imagePrompt?: T;
  audioModelId?: T;
  audioSeed?: T;
  latestAudioAsset?: T;
  latestImageAsset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  soundEffectPrompt?: T;
  imagePrompt?: T;
  audioModelId?: T;
  audioSeed?: T;
  latestAudioAsset?: T;
  latestImageAsset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-assets_select".
 */
export interface AudioAssetsSelect<T extends boolean = true> {
  assetType?: T;
  provider?: T;
  status?: T;
  sourceTextOrPrompt?: T;
  voiceId?: T;
  modelId?: T;
  durationSeconds?: T;
  seed?: T;
  media?: T;
  character?: T;
  dialogueLine?: T;
  weapon?: T;
  item?: T;
  jobID?: T;
  providerRequestID?: T;
  idempotencyKey?: T;
  errorMessage?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-assets_select".
 */
export interface ImageAssetsSelect<T extends boolean = true> {
  assetType?: T;
  provider?: T;
  status?: T;
  prompt?: T;
  model?: T;
  size?: T;
  quality?: T;
  media?: T;
  character?: T;
  weapon?: T;
  item?: T;
  jobID?: T;
  providerRequestID?: T;
  idempotencyKey?: T;
  errorMessage?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-projects_select".
 */
export interface ContentProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  status?: T;
  exportRoot?: T;
  sourceMode?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-schema-imports_select".
 */
export interface ContentSchemaImportsSelect<T extends boolean = true> {
  key?: T;
  project?: T;
  packId?: T;
  title?: T;
  kind?: T;
  exportName?: T;
  sourceFile?: T;
  bundleKey?: T;
  contentSourcePath?: T;
  schemaVersion?: T;
  schemaRef?: T;
  topLevelCounts?: T;
  canonicalDocument?: T;
  importStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-pack-documents_select".
 */
export interface ContentPackDocumentsSelect<T extends boolean = true> {
  key?: T;
  project?: T;
  schemaImport?: T;
  packId?: T;
  title?: T;
  kind?: T;
  exportName?: T;
  sourceFile?: T;
  bundleKey?: T;
  contentSourcePath?: T;
  schemaVersion?: T;
  document?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-custom-schemas_select".
 */
export interface ContentCustomSchemasSelect<T extends boolean = true> {
  key?: T;
  project?: T;
  schemaId?: T;
  name?: T;
  targetPackId?: T;
  schemaType?: T;
  document?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-platform-data_select".
 */
export interface ContentPlatformDataSelect<T extends boolean = true> {
  key?: T;
  project?: T;
  dataId?: T;
  name?: T;
  platformLayer?: T;
  namespace?: T;
  targetId?: T;
  document?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-draft-revisions_select".
 */
export interface ContentDraftRevisionsSelect<T extends boolean = true> {
  key?: T;
  project?: T;
  targetType?: T;
  targetKey?: T;
  targetName?: T;
  targetDocumentId?: T;
  changeKind?: T;
  notes?: T;
  document?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-publish-jobs_select".
 */
export interface ContentPublishJobsSelect<T extends boolean = true> {
  jobId?: T;
  project?: T;
  status?: T;
  exportRoot?: T;
  commands?: T;
  exportFiles?: T;
  engineFiles?: T;
  skippedPacks?: T;
  errorMessage?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-dialogue-audio".
 */
export interface TaskGenerateDialogueAudio {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-weapon-sfx".
 */
export interface TaskGenerateWeaponSfx {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-item-sfx".
 */
export interface TaskGenerateItemSfx {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-character-image".
 */
export interface TaskGenerateCharacterImage {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-weapon-image".
 */
export interface TaskGenerateWeaponImage {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-item-image".
 */
export interface TaskGenerateItemImage {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}