/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    docs: Doc;
    'game-traits': GameTrait;
    'narrative-entities': NarrativeEntity;
    'narrative-dialogs': NarrativeDialog;
    characters: Character;
    'dialogue-lines': DialogueLine;
    weapons: Weapon;
    items: Item;
    'audio-assets': AudioAsset;
    'image-assets': ImageAsset;
    exports: Export;
    imports: Import;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    'game-traits': GameTraitsSelect<false> | GameTraitsSelect<true>;
    'narrative-entities': NarrativeEntitiesSelect<false> | NarrativeEntitiesSelect<true>;
    'narrative-dialogs': NarrativeDialogsSelect<false> | NarrativeDialogsSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'dialogue-lines': DialogueLinesSelect<false> | DialogueLinesSelect<true>;
    weapons: WeaponsSelect<false> | WeaponsSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    'audio-assets': AudioAssetsSelect<false> | AudioAssetsSelect<true>;
    'image-assets': ImageAssetsSelect<false> | ImageAssetsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    env: Env;
  };
  globalsSelect: {
    env: EnvSelect<false> | EnvSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (PayloadMcpApiKey & {
        collection: 'payload-mcp-api-keys';
      });
  jobs: {
    tasks: {
      'generate-dialogue-audio': TaskGenerateDialogueAudio;
      'generate-weapon-sfx': TaskGenerateWeaponSfx;
      'generate-item-sfx': TaskGenerateItemSfx;
      'generate-character-image': TaskGenerateCharacterImage;
      'generate-weapon-image': TaskGenerateWeaponImage;
      'generate-item-image': TaskGenerateItemImage;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Owner: Full system access. Admin: Can create users and content. User: Read-only access. Admins will automatically create users with 'user' role.
   */
  role?: ('owner' | 'admin' | 'user') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * The display title for this category/sidebar tab
   */
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Brief description of this documentation category
   */
  description?: string | null;
  /**
   * Icon image for the category
   */
  icon?: (number | null) | Media;
  /**
   * Order in which this category appears in the sidebar
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  /**
   * The page title
   */
  title: string;
  /**
   * URL-friendly identifier for this page
   */
  slug: string;
  /**
   * Brief description or excerpt for this page
   */
  description?: string | null;
  /**
   * The sidebar tab/category this doc belongs to
   */
  category: number | Category;
  /**
   * Parent page for nested documentation structure
   */
  parent?: (number | null) | Doc;
  /**
   * Order within the category/parent
   */
  order: number;
  /**
   * The main content of the documentation page
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-traits".
 */
export interface GameTrait {
  id: number;
  name: string;
  /**
   * Stable key from game export source.
   */
  sourceKey: string;
  sourceVersion: number;
  syncedAt: string;
  /**
   * Optional source metadata from import sync.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrative-entities".
 */
export interface NarrativeEntity {
  id: number;
  name: string;
  /**
   * Stable key from game export source.
   */
  sourceKey: string;
  startingCoordinates:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  previousCoordinates:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceVersion: number;
  syncedAt: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrative-dialogs".
 */
export interface NarrativeDialog {
  id: number;
  label: string;
  phrase?: string | null;
  location:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  force:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  scenes?:
    | {
        scene: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable key from game export source.
   */
  sourceKey: string;
  sourceVersion: number;
  syncedAt: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  name: string;
  slug: string;
  summary?: string | null;
  /**
   * Optional link to imported narrative entity data.
   */
  canonicalEntity?: (number | null) | NarrativeEntity;
  traits?: (number | GameTrait)[] | null;
  /**
   * Default ElevenLabs voice for this character.
   */
  voiceId?: string | null;
  voiceModelId?: string | null;
  /**
   * Prompt used when generating portrait concept art.
   */
  portraitPrompt?: string | null;
  latestPortrait?: (number | null) | ImageAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-assets".
 */
export interface ImageAsset {
  id: number;
  assetType: 'character_portrait' | 'weapon_art' | 'item_art';
  provider: 'openai';
  status: 'queued' | 'processing' | 'succeeded' | 'failed';
  prompt: string;
  model: string;
  size: '1024x1024' | '1024x1536' | '1536x1024';
  quality: 'auto' | 'low' | 'medium' | 'high';
  media?: (number | null) | Media;
  character?: (number | null) | Character;
  weapon?: (number | null) | Weapon;
  item?: (number | null) | Item;
  jobID?: string | null;
  providerRequestID?: string | null;
  idempotencyKey?: string | null;
  errorMessage?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons".
 */
export interface Weapon {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Prompt for ElevenLabs weapon SFX generation.
   */
  soundEffectPrompt: string;
  /**
   * Prompt for OpenAI weapon art generation.
   */
  imagePrompt?: string | null;
  audioModelId?: string | null;
  audioSeed?: number | null;
  latestAudioAsset?: (number | null) | AudioAsset;
  latestImageAsset?: (number | null) | ImageAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-assets".
 */
export interface AudioAsset {
  id: number;
  assetType: 'dialogue_voice' | 'weapon_sfx' | 'item_sfx';
  provider: 'elevenlabs';
  status: 'queued' | 'processing' | 'succeeded' | 'failed';
  sourceTextOrPrompt: string;
  voiceId: string;
  modelId: string;
  durationSeconds?: number | null;
  seed?: number | null;
  media?: (number | null) | Media;
  character?: (number | null) | Character;
  dialogueLine?: (number | null) | DialogueLine;
  weapon?: (number | null) | Weapon;
  item?: (number | null) | Item;
  jobID?: string | null;
  providerRequestID?: string | null;
  idempotencyKey?: string | null;
  errorMessage?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dialogue-lines".
 */
export interface DialogueLine {
  id: number;
  label: string;
  slug: string;
  character: number | Character;
  canonicalDialog?: (number | null) | NarrativeDialog;
  scene?: string | null;
  lineText: string;
  /**
   * Optional override for ElevenLabs voice ID.
   */
  audioVoiceId?: string | null;
  /**
   * Optional override for ElevenLabs model.
   */
  audioModelId?: string | null;
  /**
   * Optional seed for deterministic generation.
   */
  audioSeed?: number | null;
  latestAudioAsset?: (number | null) | AudioAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Prompt for ElevenLabs item-use SFX generation.
   */
  soundEffectPrompt: string;
  /**
   * Prompt for OpenAI item art generation.
   */
  imagePrompt?: string | null;
  audioModelId?: string | null;
  audioSeed?: number | null;
  latestAudioAsset?: (number | null) | AudioAsset;
  latestImageAsset?: (number | null) | ImageAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format?: ('csv' | 'json') | null;
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: 'docs' | 'categories';
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  docs?: {
    /**
     * Allow clients to find docs.
     */
    find?: boolean | null;
    /**
     * Allow clients to create docs.
     */
    create?: boolean | null;
    /**
     * Allow clients to update docs.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete docs.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'docs';
    value: number | Doc;
  };
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'generate-dialogue-audio'
          | 'generate-weapon-sfx'
          | 'generate-item-sfx'
          | 'generate-character-image'
          | 'generate-weapon-image'
          | 'generate-item-image'
          | 'createCollectionExport'
          | 'createCollectionImport'
          | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'generate-dialogue-audio'
        | 'generate-weapon-sfx'
        | 'generate-item-sfx'
        | 'generate-character-image'
        | 'generate-weapon-image'
        | 'generate-item-image'
        | 'createCollectionExport'
        | 'createCollectionImport'
        | 'schedulePublish'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null)
    | ({
        relationTo: 'game-traits';
        value: number | GameTrait;
      } | null)
    | ({
        relationTo: 'narrative-entities';
        value: number | NarrativeEntity;
      } | null)
    | ({
        relationTo: 'narrative-dialogs';
        value: number | NarrativeDialog;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'dialogue-lines';
        value: number | DialogueLine;
      } | null)
    | ({
        relationTo: 'weapons';
        value: number | Weapon;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'audio-assets';
        value: number | AudioAsset;
      } | null)
    | ({
        relationTo: 'image-assets';
        value: number | ImageAsset;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  parent?: T;
  order?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-traits_select".
 */
export interface GameTraitsSelect<T extends boolean = true> {
  name?: T;
  sourceKey?: T;
  sourceVersion?: T;
  syncedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrative-entities_select".
 */
export interface NarrativeEntitiesSelect<T extends boolean = true> {
  name?: T;
  sourceKey?: T;
  startingCoordinates?: T;
  previousCoordinates?: T;
  sourceVersion?: T;
  syncedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrative-dialogs_select".
 */
export interface NarrativeDialogsSelect<T extends boolean = true> {
  label?: T;
  phrase?: T;
  location?: T;
  force?: T;
  scenes?:
    | T
    | {
        scene?: T;
        id?: T;
      };
  sourceKey?: T;
  sourceVersion?: T;
  syncedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  canonicalEntity?: T;
  traits?: T;
  voiceId?: T;
  voiceModelId?: T;
  portraitPrompt?: T;
  latestPortrait?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dialogue-lines_select".
 */
export interface DialogueLinesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  character?: T;
  canonicalDialog?: T;
  scene?: T;
  lineText?: T;
  audioVoiceId?: T;
  audioModelId?: T;
  audioSeed?: T;
  latestAudioAsset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons_select".
 */
export interface WeaponsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  soundEffectPrompt?: T;
  imagePrompt?: T;
  audioModelId?: T;
  audioSeed?: T;
  latestAudioAsset?: T;
  latestImageAsset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  soundEffectPrompt?: T;
  imagePrompt?: T;
  audioModelId?: T;
  audioSeed?: T;
  latestAudioAsset?: T;
  latestImageAsset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-assets_select".
 */
export interface AudioAssetsSelect<T extends boolean = true> {
  assetType?: T;
  provider?: T;
  status?: T;
  sourceTextOrPrompt?: T;
  voiceId?: T;
  modelId?: T;
  durationSeconds?: T;
  seed?: T;
  media?: T;
  character?: T;
  dialogueLine?: T;
  weapon?: T;
  item?: T;
  jobID?: T;
  providerRequestID?: T;
  idempotencyKey?: T;
  errorMessage?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-assets_select".
 */
export interface ImageAssetsSelect<T extends boolean = true> {
  assetType?: T;
  provider?: T;
  status?: T;
  prompt?: T;
  model?: T;
  size?: T;
  quality?: T;
  media?: T;
  character?: T;
  weapon?: T;
  item?: T;
  jobID?: T;
  providerRequestID?: T;
  idempotencyKey?: T;
  errorMessage?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  docs?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "env".
 */
export interface Env {
  id: number;
  /**
   * Key-value pairs. Use Import .env above to paste and parse.
   */
  variables?:
    | {
        envAll?: boolean | null;
        envDevelopment?: boolean | null;
        envProduction?: boolean | null;
        envStaging?: boolean | null;
        key: string;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  envContent?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "env_select".
 */
export interface EnvSelect<T extends boolean = true> {
  variables?:
    | T
    | {
        envAll?: T;
        envDevelopment?: T;
        envProduction?: T;
        envStaging?: T;
        key?: T;
        value?: T;
        id?: T;
      };
  envContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-dialogue-audio".
 */
export interface TaskGenerateDialogueAudio {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-weapon-sfx".
 */
export interface TaskGenerateWeaponSfx {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-item-sfx".
 */
export interface TaskGenerateItemSfx {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-character-image".
 */
export interface TaskGenerateCharacterImage {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-weapon-image".
 */
export interface TaskGenerateWeaponImage {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-item-image".
 */
export interface TaskGenerateItemImage {
  input: {
    generationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format?: ('csv' | 'json') | null;
    limit?: number | null;
    page?: number | null;
    sort?: string | null;
    sortOrder?: ('asc' | 'desc') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    userID?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    collectionSlug:
      | 'users'
      | 'media'
      | 'categories'
      | 'docs'
      | 'game-traits'
      | 'narrative-entities'
      | 'narrative-dialogs'
      | 'characters'
      | 'dialogue-lines'
      | 'weapons'
      | 'items'
      | 'audio-assets'
      | 'image-assets'
      | 'exports'
      | 'imports';
    importMode?: ('create' | 'update' | 'upsert') | null;
    matchField?: string | null;
    status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
    summary?: {
      imported?: number | null;
      updated?: number | null;
      total?: number | null;
      issues?: number | null;
      issueDetails?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    user?: string | null;
    userCollection?: string | null;
    importsCollection?: string | null;
    file?: {
      data?: string | null;
      mimetype?: string | null;
      name?: string | null;
    };
    format?: ('csv' | 'json') | null;
    debug?: boolean | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'docs';
      value: number | Doc;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}