export type {
  CombatStatPackDocument,
  ContentPackRegistryEntry,
  ContentPackRegistryKind,
  ContentPackBundle,
  ContentSchemaDocument,
  ContentSourceDocument,
  EffectPackDocument,
  EquipmentSlotPackDocument,
  EntityTypePackDocument,
  GameStatsDocument,
  GuidePackDocument,
  MountPackDocument,
  NarrativeStatPackDocument,
  OccupationPackDocument,
  PartyRolePackDocument,
  RuntimeEntityIdentityPackDocument,
  RarityPackDocument,
  RuneAffinityPackDocument,
  RunePackDocument,
  SkillStatPackDocument,
  SpawnTableDocument,
  StatSchemaDocument,
  SpellCategoryPackDocument,
  SpellEvolutionPackDocument,
  SpellForgeCostsDocument,
  SpellPackDocument,
  SpellProgressionPackDocument,
  TitlePackDocument,
  WorldMapRegion,
  WorldMapPackDocument,
} from "./escape-the-dungeon/contracts";
export {
  ACTION_CATALOG,
  ACTION_CATALOG_BY_ACTION_TYPE,
  ACTION_CATALOG_LIST,
  ACTION_CONTRACTS,
  ACTION_INTENTS,
  ACTION_INTENT_BY_ACTION_TYPE,
  ACTION_INTENT_LIST,
  ACTION_POLICIES,
  ACTION_POLICY_BY_ID,
  ACTION_POLICY_LIST,
  ARCHETYPE_PACK,
  ARCHETYPE_BY_ID,
  ARCHETYPE_LIST,
  CANONICAL_SEED_V1,
  COMBAT_STAT_PACK,
  COMBAT_STAT_BY_ID,
  COMBAT_STAT_BY_KEY,
  COMBAT_STAT_LIST,
  COMBAT_STAT_NAME_BY_ID,
  CONTENT_PACK_REGISTRY,
  CONTENT_SCHEMA_DOCUMENT,
  CONTENT_SOURCE_DOCUMENT,
  CUTSCENE_PACK,
  CUTSCENE_BY_ID,
  CUTSCENE_LIST,
  DUNGEON_LAYOUT_BY_TITLE,
  DIALOGUE_PACK,
  DIALOGUE_BY_ID,
  DIALOGUE_LIST,
  DUNGEON_LAYOUT_PACK,
  DUNGEON_LAYOUT_LIST,
  DUNGEON_ROOM_BY_ID,
  DUNGEON_ROOM_LIST,
  decodeContentPackBundle,
  decodeContentSourceDocument,
  EFFECT_BY_ID,
  EFFECT_LIST,
  EFFECT_NAME_BY_ID,
  EFFECT_PACK,
  EQUIPMENT_SLOT_BY_ID,
  EQUIPMENT_SLOT_LIST,
  EQUIPMENT_SLOT_NAME_BY_ID,
  EQUIPMENT_SLOT_PACK,
  ENTITY_TYPE_PACK,
  ENTITY_TYPE_BY_ID,
  ENTITY_TYPE_LIST,
  ENTITY_TYPE_NAME_BY_ID,
  EVENT_PACK,
  EVENT_BY_ID,
  EVENT_LIST,
  GAME_STATS,
  GUIDE_BY_ID,
  GUIDE_PACK,
  GUIDE_LIST,
  GUIDE_TITLE_BY_ID,
  ITEM_PACK,
  ITEM_BY_ID,
  ITEM_LIST,
  ITEM_NAME_BY_ID,
  MOUNT_PACK,
  MOUNT_BY_ID,
  MOUNT_LIST,
  MOUNT_NAME_BY_ID,
  NARRATIVE_STAT_PACK,
  NARRATIVE_STAT_BY_ID,
  NARRATIVE_STAT_BY_KEY,
  NARRATIVE_STAT_LIST,
  NARRATIVE_STAT_NAME_BY_ID,
  OCCUPATION_BY_ID,
  OCCUPATION_LIST,
  OCCUPATION_NAME_BY_ID,
  OCCUPATION_PACK,
  PARTY_ROLE_BY_ID,
  PARTY_ROLE_LIST,
  PARTY_ROLE_NAME_BY_ID,
  PARTY_ROLE_PACK,
  RUNTIME_ENTITY_IDENTITY_HOSTILE_OVERRIDE_BY_ARCHETYPE_ID,
  RUNTIME_ENTITY_IDENTITY_HOSTILE_OVERRIDE_LIST,
  RUNTIME_ENTITY_IDENTITY_PACK,
  RUNTIME_ENTITY_IDENTITY_PRESET_BY_ID,
  RUNTIME_ENTITY_IDENTITY_PRESET_LIST,
  QUEST_PACK,
  QUEST_BY_ID,
  QUEST_LIST,
  RARITY_PACK,
  RARITY_BY_ID,
  RARITY_LABEL_BY_ID,
  RARITY_LIST,
  ROOM_TEMPLATE_BY_FEATURE,
  ROOM_TEMPLATE_LIST,
  ROOM_TEMPLATES,
  RUNE_AFFINITY_PACK,
  RUNE_PACK,
  RUNE_BY_ID,
  RUNE_LIST,
  RUNE_NAME_BY_ID,
  SKILL_STAT_PACK,
  SKILL_STAT_BY_ID,
  SKILL_STAT_BY_KEY,
  SKILL_STAT_LIST,
  SKILL_STAT_NAME_BY_ID,
  SKILL_PACK,
  SKILL_BY_ID,
  SKILL_LIST,
  SKILL_NAME_BY_ID,
  SPAWN_TABLE_PACK,
  SPELL_CATEGORY_PACK,
  SPELL_CATEGORY_BY_ID,
  SPELL_CATEGORY_LIST,
  SPELL_CATEGORY_NAME_BY_ID,
  SPELL_EVOLUTION_PACK,
  SPELL_EVOLUTION_BY_ID,
  SPELL_EVOLUTION_LIST,
  SPELL_FORGE_COSTS,
  SPELL_PACK,
  SPELL_BY_ID,
  SPELL_BY_RUNE_COMBO_KEY,
  SPELL_LIST,
  SPELL_NAME_BY_ID,
  SPELL_PROGRESSION_PACK,
  STAT_SCHEMA_DOCUMENT,
  THE_MOUNT,
  TITLE_PACK,
  TITLE_BY_ID,
  TITLE_LIST,
  TITLE_NAME_BY_ID,
  WORLD_PLACE_BY_ID,
  WORLD_PLACE_LIST,
  WORLD_PLACE_NAME_BY_ID,
  WORLD_MAP_PACK,
  WORLD_REGION_BY_ID,
  WORLD_REGION_LIST,
  WORLD_REGION_NAME_BY_ID,
} from "./escape-the-dungeon/contracts";
export { DeterministicRng } from "./escape-the-dungeon/core/rng";
export type {
  ActionAvailability,
  CombatStatKey,
  CombatStatMap,
  DeedMemory,
  EntityState,
  FeatureVector,
  GameConfig,
  GameEvent,
  GameSnapshot,
  GameState,
  MoveDirection,
  NarrativeStatMap,
  NarrativeStatName,
  NumberMap,
  PlayerAction,
  PlayerActionType,
  RoomFeature,
  RuneStatId,
  SkillStatKey,
  SkillStatMap,
  Transform3d,
  TraitVector,
  TurnResult,
  Vec3,
} from "./escape-the-dungeon/core/types";
export {
  ACTION_TYPE,
  createCombatStats,
  createNarrativeStats,
  createSkillStats,
  createTransform,
  createVec3,
  DEFAULT_GAME_CONFIG,
  PLAYER_ACTION_TYPES,
  ROOM_FEATURES,
  TRAIT_NAMES,
} from "./escape-the-dungeon/core/types";
export { GameEngine } from "./escape-the-dungeon/engine/game";
export {
  FORMULA_REGISTRY_VERSION,
  formulaRegistry,
} from "./escape-the-dungeon/formulas/registry";
export type { PersistenceAdapter } from "./escape-the-dungeon/persistence/indexeddb";
export { createPersistence } from "./escape-the-dungeon/persistence/indexeddb";
export type {
  BalanceBatchMetrics,
  BalanceRunMetrics,
  LongRunSuiteMetrics,
  LongRunWindowMetrics,
} from "./escape-the-dungeon/simulation/harness";
export {
  simulateBalanceBatch,
  simulateBalanceRun,
  simulateLongRunSuite,
} from "./escape-the-dungeon/simulation/harness";
export type {
  ActionSpacePoint,
  BehaviorSignature,
  BehaviorStyle,
  BehaviorTimelinePoint,
  EffectSpacePoint,
  EventSpacePoint,
  RoomSpacePoint,
  RuntimeFeatureDefinition,
  RuntimeModelDefinition,
  SpaceVectorPackOverrides,
  UnifiedSpaceModel,
  UnifiedSpaceVector,
} from "./escape-the-dungeon/spaces/model";
export {
  behaviorSimilarity,
  buildModelFeatureVector,
  buildUnifiedSpaceModel,
  CONTENT_FEATURES_V1,
  contentFeaturesFromGeneratedSlice,
  getFeatureSchema,
  getModelFeatureIds,
  getModelFeatureRefs,
  getModelSchemas,
  getSpaceFeatureIds,
  POWER_FEATURES_V1,
  projectEntitySpaceVector,
  projectItemSpaceVector,
  projectLevelSpaceVector,
  resolveSpaceVectorPack,
  THEMATIC_BASIS_TRAITS_V1,
  thematicBasisTraitsFromGeneratedSlice,
  UNIFIED_SPACE_MODEL_V1,
  withContentFeaturesFromGeneratedSlice,
  withThematicBasisFromGeneratedSlice,
} from "./escape-the-dungeon/spaces/model";
export {
  buildActionGroups,
  extractCutsceneQueue,
  initialFeed,
  toFeedMessages,
} from "./escape-the-dungeon/ui/presenter";
export type {
  ActionGroup,
  ActionItem,
  CutsceneMessage,
  FeedMessage,
  PlayUiAction,
} from "./escape-the-dungeon/ui/types";
export {
  buildDungeonLayoutSnapshot,
  type DungeonLayoutSnapshot,
  type LayoutDungeon,
  type LayoutEntity,
  type LayoutLevel,
  type LayoutRoom,
} from "./escape-the-dungeon/world/layout";
export {
  buildDungeonWorld,
  getLevel,
  getRoom,
  ROOM_FEATURE_COMBAT,
  ROOM_FEATURE_REST,
  ROOM_FEATURE_RUNE_FORGE,
  ROOM_FEATURE_TRAINING,
  ROOM_FEATURE_TREASURE,
  roomCenterPosition,
} from "./escape-the-dungeon/world/map";
export {
  normalizeEntityStats,
} from "./escape-the-dungeon/core/entity-stat-domains";
export {
  adjustCombatStat,
  adjustNarrativeStat,
  adjustRuneStat,
  combatStat,
  currentHp,
  currentMana,
  isAlive,
  narrativeStat,
  runeStat,
  setCombatStat,
  setCurrentHp,
  setCurrentMana,
  setNarrativeStat,
  setRuneStat,
  setSkillStat,
  skillStat,
} from "./escape-the-dungeon/core/entity-stats";
export {
  COMBAT_STAT_DEFAULTS,
  COMBAT_STAT_ID_TO_KEY,
  COMBAT_STAT_IDS,
  COMBAT_STAT_KEYS,
  NARRATIVE_STAT_DEFAULTS,
  NARRATIVE_STAT_ID_TO_KEY,
  NARRATIVE_STAT_IDS,
  NARRATIVE_STAT_NAMES,
  RUNE_IDS,
  SKILL_STAT_DEFAULTS,
  SKILL_STAT_ID_TO_KEY,
  SKILL_STAT_IDS,
  SKILL_STAT_KEYS,
} from "./escape-the-dungeon/contracts/generated/stat-keys";
export type { DungeonBreakGameProps } from "./react/DungeonBreakGame";
export { DungeonBreakGame } from "./react/DungeonBreakGame";
