export type {
  ContentPackBundle,
  ContentSchemaDocument,
  ContentSourceDocument,
  EntityTypePackDocument,
  GameStatsDocument,
  GuidePackDocument,
  MountPackDocument,
  RarityPackDocument,
  RuneAffinityPackDocument,
  RunePackDocument,
  SpaceVectorPack,
  SpellCategoryPackDocument,
  SpellEvolutionPackDocument,
  SpellPackDocument,
  SpellProgressionPackDocument,
  TitlePackDocument,
  WorldMapRegion,
  WorldMapPackDocument,
} from "./escape-the-dungeon/contracts";
export {
  ACTION_CATALOG,
  ACTION_CONTRACTS,
  ACTION_INTENTS,
  ACTION_POLICIES,
  ARCHETYPE_PACK,
  CANONICAL_SEED_V1,
  CONTENT_SCHEMA_DOCUMENT,
  CONTENT_SOURCE_DOCUMENT,
  CUTSCENE_PACK,
  DIALOGUE_PACK,
  DUNGEON_LAYOUT_PACK,
  decodeContentPackBundle,
  decodeContentSourceDocument,
  ENTITY_TYPE_PACK,
  EVENT_PACK,
  GAME_STATS,
  GUIDE_PACK,
  ITEM_PACK,
  MOUNT_PACK,
  QUEST_PACK,
  RARITY_PACK,
  ROOM_TEMPLATES,
  RUNE_AFFINITY_PACK,
  RUNE_PACK,
  SKILL_PACK,
  SPACE_VECTOR_PACK,
  SPELL_CATEGORY_PACK,
  SPELL_EVOLUTION_PACK,
  SPELL_PACK,
  SPELL_PROGRESSION_PACK,
  THE_MOUNT,
  TITLE_PACK,
  WORLD_MAP_PACK,
} from "./escape-the-dungeon/contracts";
export { DeterministicRng } from "./escape-the-dungeon/core/rng";
export type {
  ActionAvailability,
  DeedMemory,
  EntityState,
  FeatureVector,
  GameConfig,
  GameEvent,
  GameSnapshot,
  GameState,
  MoveDirection,
  NumberMap,
  PlayerAction,
  PlayerActionType,
  RoomFeature,
  Transform3d,
  TurnResult,
  Vec3,
} from "./escape-the-dungeon/core/types";
export {
  ACTION_TYPE,
  createTransform,
  createVec3,
  DEFAULT_GAME_CONFIG,
  FEATURE_NAMES,
  PLAYER_ACTION_TYPES,
  ROOM_FEATURES,
  TRAIT_NAMES,
} from "./escape-the-dungeon/core/types";
export { GameEngine } from "./escape-the-dungeon/engine/game";
export {
  FORMULA_REGISTRY_VERSION,
  formulaRegistry,
} from "./escape-the-dungeon/formulas/registry";
export type { PersistenceAdapter } from "./escape-the-dungeon/persistence/indexeddb";
export { createPersistence } from "./escape-the-dungeon/persistence/indexeddb";
export type {
  BalanceBatchMetrics,
  BalanceRunMetrics,
  LongRunSuiteMetrics,
  LongRunWindowMetrics,
} from "./escape-the-dungeon/simulation/harness";
export {
  simulateBalanceBatch,
  simulateBalanceRun,
  simulateLongRunSuite,
} from "./escape-the-dungeon/simulation/harness";
export type {
  ActionSpacePoint,
  BehaviorSignature,
  BehaviorStyle,
  BehaviorTimelinePoint,
  EffectSpacePoint,
  EventSpacePoint,
  RoomSpacePoint,
  RuntimeFeatureDefinition,
  RuntimeModelDefinition,
  SpaceVectorPackOverrides,
  UnifiedSpaceModel,
  UnifiedSpaceVector,
} from "./escape-the-dungeon/spaces/model";
export {
  behaviorSimilarity,
  buildModelFeatureVector,
  buildUnifiedSpaceModel,
  CONTENT_FEATURES_V1,
  contentFeaturesFromGeneratedSlice,
  getFeatureSchema,
  getModelFeatureIds,
  getModelFeatureRefs,
  getModelSchemas,
  getSpaceFeatureIds,
  POWER_FEATURES_V1,
  projectEntitySpaceVector,
  projectItemSpaceVector,
  projectLevelSpaceVector,
  resolveSpaceVectorPack,
  THEMATIC_BASIS_TRAITS_V1,
  thematicBasisTraitsFromGeneratedSlice,
  UNIFIED_SPACE_MODEL_V1,
  withContentFeaturesFromGeneratedSlice,
  withThematicBasisFromGeneratedSlice,
} from "./escape-the-dungeon/spaces/model";
export {
  buildActionGroups,
  extractCutsceneQueue,
  initialFeed,
  toFeedMessages,
} from "./escape-the-dungeon/ui/presenter";
export type {
  ActionGroup,
  ActionItem,
  CutsceneMessage,
  FeedMessage,
  PlayUiAction,
} from "./escape-the-dungeon/ui/types";
export {
  buildDungeonLayoutSnapshot,
  type DungeonLayoutSnapshot,
  type LayoutDungeon,
  type LayoutEntity,
  type LayoutLevel,
  type LayoutRoom,
} from "./escape-the-dungeon/world/layout";
export {
  buildDungeonWorld,
  getLevel,
  getRoom,
  ROOM_FEATURE_COMBAT,
  ROOM_FEATURE_REST,
  ROOM_FEATURE_RUNE_FORGE,
  ROOM_FEATURE_TRAINING,
  ROOM_FEATURE_TREASURE,
  roomCenterPosition,
} from "./escape-the-dungeon/world/map";
export type { DungeonBreakGameProps } from "./react/DungeonBreakGame";
export { DungeonBreakGame } from "./react/DungeonBreakGame";
