import {
	DocsBody,
	DocsDescription,
	DocsPage,
	DocsTitle,
} from "fumadocs-ui/page";
import Link from "next/link";

export const metadata = {
	title: "Getting Started",
	description:
		"DungeonBreak — linear world, branching narrative RPG. This site hosts docs, API references, and onboarding.",
};

export default function GettingStartedPage() {
	return (
		<DocsPage footer={{ enabled: false }} tableOfContent={{ style: "normal", single: false }} toc={[]}>
			<DocsTitle className="font-bold font-serif text-4xl md:text-5xl">
				Getting Started
			</DocsTitle>
			<DocsDescription>
				DungeonBreak — linear world, branching narrative RPG. This site hosts docs, API references, and onboarding.
			</DocsDescription>
			<DocsBody>
				<div className="fd-prose">
					<h2>DungeonBreak</h2>
					<p>
						DungeonBreak is a linear world, branching narrative RPG: emergent, system-driven, with tactical RTS-lite combat, rich dialog, and alignment. Pillars: fixed A-to-B world with branching human path; stop the Dungeon Breaks; TTRPG feel (walk and talk, companions); character-driven emergence (time-spend simulation).
					</p>
					<h3>What&apos;s in this doc site</h3>
					<p>Use the sidebar to browse:</p>
					<ul>
						<li>
							<Link href="/docs/api">API</Link> — C++ and Python API reference (generated by <code>npm run docs:generate</code>).
						</li>
						<li>
							<Link href="/docs/guides/onboarding">Guides</Link> — onboarding and finding code (e.g. Onboarding).
						</li>
					</ul>
					<p>
						Run <code>npm run lab</code> (or at least <code>npm run docs:generate</code>) so that API and guides appear in the sidebar and are up to date.
					</p>
				</div>
			</DocsBody>
		</DocsPage>
	);
}
